run:
  tests: true
  #modules-download-mode: vendor
  skip-dirs:
  - vendor
linters:
  disable-all: true
  enable:
  - deadcode
  - errcheck
  - goconst
  - gofumpt
  - goimports
  - golint
  - gosec
  - gosimple
  - govet
  - ineffassign
  - nakedret
  - staticcheck
  - structcheck
  - unused
  - varcheck
  - whitespace
linters-settings:
  govet:
    check-shadowing: true
issues:
  exclude-use-default: false
  exclude:
  - Error return value of .((os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
  - 'shadow: declaration of "err" shadows declaration at line (\d+)'
  - 'SA1019: package github.com/golang/protobuf/(.*) is deprecated:'
  - 'SA1019: grpc.CustomCodec is deprecated'
  - 'G104: Errors unhandled'
